x-common:
  &default
  image: run-tests:v1
  volumes:
    - ./:/usr/workspace
  working_dir: /usr/workspace

services:

  api-tests:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "pytest"
      - "-v"
      - "--alluredir=allure-results"
      - "tests/api_tests"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

  ui-tests-alerts-frame-windows:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/alerts_frame_windows_test.py"

  ui-tests-book-store-application:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/book_store_application_test.py"
    environment:
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}

  ui-tests-elements:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/elements_test.py"

  ui-tests-forms:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/forms_test.py"

  ui-tests-interactions:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/interactions_test.py"

  ui-tests-widgets:
    <<: *default
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=eager"
      - "--alluredir=allure-results"
      - "tests/ui_tests/widgets_test.py"
