services:

  api-tests:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
    command:
      - "pytest"
      - "-v"
      - "--alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

  ui-tests:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile.ui
    volumes:
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
    command:
      - "pytest"
      - "-sv"
      - "--headless"
      - "--browser=chrome"
      - "--page_load_strategy=normal"
      - "--alluredir=allure-results"
      - "tests/alerts_frame_windows_test.py"
    working_dir: /usr/workspace
    environment:
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
