FROM python:3.12-alpine3.20

WORKDIR /usr/workspace

COPY requirements.txt .
COPY tests/api_tests/conftest.py .
COPY base/ base/
COPY config/ config/
COPY services/ services/
COPY utils/ utils/
COPY generator/ generator/

RUN pip install -r requirements.txt