name: Run Tests on Book Store Application Branch

on:
  push:
    branches:
      - feature/tests-book-store-application
  pull_request:
    branches:
      - feature/tests-book-store-application

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pytest -s --headless tests/book_store_application_test.py
        continue-on-error: true