name: Test Page and Browser Selection

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select the page to be tested
        required: true
        default: Browser Windows Page
        type: choice
        options:
          - Browser Windows Page
          - Alerts Page
          - Frames Page
          - Nested Frames Page
          - Modal Dialogs Page
      browser:
        description: Choose browser
        required: true
        default: chrome
        type: choice
        options:
          - chrome
          - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        if: github.event.inputs.browser == 'chrome'
        run: sudo apt-get install google-chrome-stable

      - name: Install Mozilla Firefox
        if: github.event.inputs.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Determine test case
        id: set-test
        run: |
          TARGET="${{ github.event.inputs.deployment_target }}"
          TEST_NAME="Test${TARGET// /}"
          echo "TEST_NAME=$TEST_NAME" >> $GITHUB_ENV
          echo "BROWSER=${{ github.event.inputs.browser }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest -s --headless --browser $BROWSER tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::$TEST_NAME
        continue-on-error: true